### ISSUE TITLE
还有更新吗

### ISSUE THREAD

**Issue by GentleCP** [Vancir/Awesome-Software-Supply-Chain-Security#1]
这个项目很好呀，作者还会更新吗？

**Comment by Vancir** [comment]
谢谢关注，这是我在去年搜集的一些材料。实际上过去这一年来供应链安全事件发生的比以往都要频繁得多，我后续会持续进行更新，也欢迎提交PR。

**Comment by GentleCP** [comment]
好的，期待更多精彩内容！🤓
